### PR TITLE
fix: add better error logging for Plus quality Mux videos

### LINKED ISSUE #34: Plus tier assets serve HLS with .ts (MPEG-TS) segments
We integrated @mux/mux-background-video into our Next.js 16 site for hero background videos. The component works perfectly with Premium-tier assets but fails completely with Plus—tier assets, and the failure mode is severe.

The problem:

Plus tier assets serve HLS with .ts (MPEG-TS) segments. The library's HLS mini engine tries to feed these into a MediaSource buffer, which rejects them because it expects fMP4. But instead of detecting the incompatible format and falling back or erroring, the component enters an infinite retry loop on a 500ms interval. This floods the network tab with hundreds of failed segment fetches per minute while showing nothing but the poster image.

What we observed:
- Master manifest fetches successfully (200)
- Rendition manifest fetches successfully (200)
- .ts segment fetch succeeds (200) but appendBuffer silently fails
- 500ms interval retries the same segments endlessly
- Network tab fills with thousands of requests
- No error logged, no event emitted — completely silent failure
- Video never plays, poster stays frozen

What we expected:
- Either a clear error/warning: "This playback ID uses .ts segments which are not supported. Use Premium tier or fall back to MP4."
- Or graceful fallback to the static MP4 rendition
- At minimum, stop retrying after N failures instead of looping forever

The docs do mention the Basic/Premium requirement, but:
1. Plus tier also uses .ts segments — the docs don't make this clear (they only mention "Basic")
2. A silent infinite loop is never an acceptable failure mode, regardless of what the docs say

Our environment:
- @mux/mux-background-video (latest as of April 2026)
- Next.js 16, React 19
- Chrome 146, Safari 18

Reproduction:
# Plus tier manifest — .ts segments, breaks the component
curl [https://stream.mux.com/{plus-tier-playback-id}.m3u8](https://stream.mux.com/%7Bplus-tier-playback-id%7D.m3u8)

# Premium tier manifest — .m4s segments, works fine
curl [https://stream.mux.com/{premium-tier-playback-id}.m3u8](https://stream.mux.com/%7Bpremium-tier-playback-id%7D.m3u8)

Suggestions:
1. Detect .ts segments before attempting playback and throw a meaningful error
2. Add a max retry count or exponential backoff instead of infinite 500ms polling
3. Consider auto-falling back to mp4 when HLS segments are incompatible
4. Update docs to clarify that Plus tier is also incompatible, not just Basic

### PR DESCRIPTION
**Pull request by Jerricho93**
Closes #34 

Added better error logging for TS segments

---

> [!NOTE]
> **Medium Risk**
> Introduces stricter playlist validation that can cause previously attempted streams to fail earlier, so compatibility depends on the init-segment heuristic being correct; otherwise changes are limited to logging/error handling.
> 
> **Overview**
> Improves failure visibility when loading HLS sources by logging top-level `loadMedia` failures (instead of rethrowing as an unhandled rejection) and ignoring errors triggered by abort/unload.
> 
> Adds an explicit guard in `getMediaPlaylist` to reject non-fMP4 media playlists (missing an init segment), producing a clear error that points to Mux quality tier docs; the README is updated to clearly state that Mux Plus/classic HLS (`.ts` segments) is not supported. Also tweaks the interval timer typing in `mediasource.ts` for broader TS compatibility.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 2a429575bcf425118730f2898eb65cdc5a285f90. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Review by spuppo-mux — APPROVED** [review]

**Review by spuppo-mux — APPROVED** [review]

File: src/engines/hls-mini/playlists.ts [hunk 1]
```diff
@@ -126,9 +126,37 @@ export const getMediaPlaylist = async <T extends Rendition>(
...
+      hint = ' (MPEG-TS .ts segments detected)';
+    }
+  } catch {
+    // URL parsing failed — not critical, leave hint empty.
+  }
+
+  throw new Error(
+    `Unsupported HLS segment format${hint}: this engine requires fMP4 (CMAF) ` +
+    'segments with an #EXT-X-MAP init segment. For Mux streams, use Basic or ' +
+    'Premium video quality. See https://www.mux.com/docs/guides/use-video-quality-levels'
```
Comment (luwes) [inline src/engines/hls-mini/playlists.ts]: this adds quite a lot of weight for logging an error, since it's the main goal of this engine could this be made a bit more compact?

**Review by luwes — APPROVED** [review]
LGTM thanks!
